name: python-tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight UTC

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      id: build_image  # This id is necessary to refer to this step's output later
      run: |
        IMAGE_TAG=my-image-name:$(date +%s)  # Save the tag to a variable
        docker build . --file Dockerfile --tag $IMAGE_TAG  # Use the tag for the build
        echo "IMAGE_TAG=$IMAGE_TAG"  # Print the tag to the logs (optional)
        echo "::set-output name=image_tag::$IMAGE_TAG"  # Save the tag as an output for later use

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image to Docker Hub or GitHub Container Registry
      run: |
        IMAGE_TAG=${{ steps.build_image.outputs.image_tag }}  # Correct syntax for accessing step output
        echo "Pushing image with tag: $IMAGE_TAG"  # Optional: Print the tag to the logs
        docker push $IMAGE_TAG  # Push using the same tag
