name: python-tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight UTC

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=my-image-name:$(date +%s) # Save the tag to a variable
        docker build . --file Dockerfile --tag $IMAGE_TAG # Use the tag for the build
        echo "::set-output name=image_tag::$IMAGE_TAG" # Save the tag as an output for later use

  # Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  # Push the Docker image
    - name: Push the Docker image to Docker Hub or GitHub Container Registry
      run: |
        IMAGE_TAG=$(echo ${{ steps.build_image.outputs.image_tag }})  # Get the tag from the build step
        docker push $IMAGE_TAG  # Push using the same tag