name: python-tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight UTC

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  # Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  # Push the Docker image
    - name: Push the Docker image to Docker Hub or GitHub Container Registry
      run: docker push my-image-name:$(date +%s)